version: '3.8'

services:
  client:
    build: ./example-project
    ports:
      - "5173:5173"

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nipa-ticket
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  koaserver:
    build: ./koaserver
    ports:
      - "5000:5000"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: nipa-ticket

networks:
  default:
    driver: bridge
volumes:
  postgres_data:
